#!/usr/bin/env bash
#
# Script emulating OVH post-installation script procedure

SCRIPT_URL="https://raw.githubusercontent.com/MatthieuMichon/post-config/master/scripts/ovh/ovh"

bash -c (exec 2>&1 ; PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sfw/bin/ ;echo Getting script :; wget --no-check-certificate -O /tmp/script $SCRIPT_URL && chmod a+x /tmp/script && echo Executing script : && /tmp/script ; rm /tmp/script) | tee /tmp/return.txt
