#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# Common Debian based host tasks
# - Install base packages
# - User parameters


do_upgrade () {
  apt-get --assume-yes update
  apt-get --assume-yes upgrade
  apt-get --assume-yes dist-upgrade
}


fix_locales () {
  sed -i -e 's/^en_GB/# en_GB/' /etc/locale.gen
  sed -i -e 's/en_GB/en_US/' /etc/default/locale
  sed -i -e 's/# LANG/LANG/' /etc/default/locale
  dpkg-reconfigure --frontend=noninteractive locales
}


main () {
  do_upgrade
  fix_locales
  touch ovh_debian_done
}


main
