#!/usr/bin/env bash
#
# Post-installation Configuration Scripts
#
# OVH-specific actions for Debian based hosts
# - Fix locals


fix_locales () {
  sed -i -e 's/^en_GB/# en_GB/' /etc/locale.gen
  sed -i -e 's/en_GB/en_US/' /etc/default/locale
  sed -i -e 's/# LANG/LANG/' /etc/default/locale
  dpkg-reconfigure --frontend=noninteractive locales
}


main () {
  fix_locales
  touch ovh_debian_done
}


main
